const HIRAGANA_DATA = {
  "Hiragana Gojūon": {
    "あ": { romaji: ["a"] }, "い": { romaji: ["i"] }, "う": { romaji: ["u"] }, "え": { romaji: ["e"] }, "お": { romaji: ["o"] },
    "か": { romaji: ["ka"] }, "き": { romaji: ["ki"] }, "く": { romaji: ["ku"] }, "け": { romaji: ["ke"] }, "こ": { romaji: ["ko"] },
    "さ": { romaji: ["sa"] }, "し": { romaji: ["shi"] }, "す": { romaji: ["su"] }, "せ": { romaji: ["se"] }, "そ": { romaji: ["so"] },
    "た": { romaji: ["ta"] }, "ち": { romaji: ["chi"] }, "つ": { romaji: ["tsu"] }, "て": { romaji: ["te"] }, "と": { romaji: ["to"] },
    "な": { romaji: ["na"] }, "に": { romaji: ["ni"] }, "ぬ": { romaji: ["nu"] }, "ね": { romaji: ["ne"] }, "の": { romaji: ["no"] },
    "は": { romaji: ["ha"] }, "ひ": { romaji: ["hi"] }, "ふ": { romaji: ["fu"] }, "へ": { romaji: ["he"] }, "ほ": { romaji: ["ho"] },
    "ま": { romaji: ["ma"] }, "み": { romaji: ["mi"] }, "む": { romaji: ["mu"] }, "め": { romaji: ["me"] }, "も": { romaji: ["mo"] },
    "や": { romaji: ["ya"] }, "ゆ": { romaji: ["yu"] }, "よ": { romaji: ["yo"] },
    "ら": { romaji: ["ra"] }, "り": { romaji: ["ri"] }, "る": { romaji: ["ru"] }, "れ": { romaji: ["re"] }, "ろ": { romaji: ["ro"] },
    "わ": { romaji: ["wa"] }, "を": { romaji: ["wo", "o"] }, "ん": { romaji: ["n"] }
  },

  "Hiragana Dakuon": {
    "が": { romaji: ["ga"] }, "ぎ": { romaji: ["gi"] }, "ぐ": { romaji: ["gu"] }, "げ": { romaji: ["ge"] }, "ご": { romaji: ["go"] },
    "ざ": { romaji: ["za"] }, "じ": { romaji: ["ji"] }, "ず": { romaji: ["zu"] }, "ぜ": { romaji: ["ze"] }, "ぞ": { romaji: ["zo"] },
    "だ": { romaji: ["da"] }, "ぢ": { romaji: ["ji"] }, "づ": { romaji: ["zu"] }, "で": { romaji: ["de"] }, "ど": { romaji: ["do"] },
    "ば": { romaji: ["ba"] }, "び": { romaji: ["bi"] }, "ぶ": { romaji: ["bu"] }, "べ": { romaji: ["be"] }, "ぼ": { romaji: ["bo"] },
    "ぱ": { romaji: ["pa"] }, "ぴ": { romaji: ["pi"] }, "ぷ": { romaji: ["pu"] }, "ぺ": { romaji: ["pe"] }, "ぽ": { romaji: ["po"] }
  },

  "Hiragana Yōon": {
    "きゃ": { romaji: ["kya"] }, "きゅ": { romaji: ["kyu"] }, "きょ": { romaji: ["kyo"] },
    "しゃ": { romaji: ["sha"] }, "しゅ": { romaji: ["shu"] }, "しょ": { romaji: ["sho"] },
    "ちゃ": { romaji: ["cha"] }, "ちゅ": { romaji: ["chu"] }, "ちょ": { romaji: ["cho"] },
    "にゃ": { romaji: ["nya"] }, "にゅ": { romaji: ["nyu"] }, "にょ": { romaji: ["nyo"] },
    "ひゃ": { romaji: ["hya"] }, "ひゅ": { romaji: ["hyu"] }, "ひょ": { romaji: ["hyo"] },
    "みゃ": { romaji: ["mya"] }, "みゅ": { romaji: ["myu"] }, "みょ": { romaji: ["myo"] },
    "りゃ": { romaji: ["rya"] }, "りゅ": { romaji: ["ryu"] }, "りょ": { romaji: ["ryo"] },
    "ぎゃ": { romaji: ["gya"] }, "ぎゅ": { romaji: ["gyu"] }, "ぎょ": { romaji: ["gyo"] },
    "じゃ": { romaji: ["ja"] }, "じゅ": { romaji: ["ju"] }, "じょ": { romaji: ["jo"] },
    "びゃ": { romaji: ["bya"] }, "びゅ": { romaji: ["byu"] }, "びょ": { romaji: ["byo"] },
    "ぴゃ": { romaji: ["pya"] }, "ぴゅ": { romaji: ["pyu"] }, "ぴょ": { romaji: ["pyo"] }
  },
 
 "Vocabulary (Hiragana)": {
    // --- ANIMALS (どうぶつ) ---
    "ねこ": { romaji: ["neko"], meaning: "cat" },
    "いぬ": { romaji: ["inu"], meaning: "dog" },
    "とり": { romaji: ["tori"], meaning: "bird" },
    "うさぎ": { romaji: ["usagi"], meaning: "rabbit" },
    "からす": { romaji: ["karasu"], meaning: "crow" },
    "きつね": { romaji: ["kitsune"], meaning: "fox" },
    "すずめ": { romaji: ["suzume"], meaning: "sparrow" },
    "たぬき": { romaji: ["tanuki"], meaning: "raccoon dog" },
    "ねずみ": { romaji: ["nezumi"], meaning: "mouse" },
    "ひつじ": { romaji: ["hitsuji"], meaning: "sheep" },
    "めだか": { romaji: ["medaka"], meaning: "killifish" },
    "くじら": { romaji: ["kujira"], meaning: "whale" },

    // --- NATURE & WEATHER (しぜん・てんき) ---
    "さくら": { romaji: ["sakura"], meaning: "cherry blossom" },
    "ひまわり": { romaji: ["himawari"], meaning: "sunflower" },
    "あさがお": { romaji: ["asagao"], meaning: "morning glory" },
    "もみじ": { romaji: ["momiji"], meaning: "maple" },
    "たけのこ": { romaji: ["takenoko"], meaning: "bamboo shoot" },
    "かみなり": { romaji: ["kaminari"], meaning: "thunder" },
    "みずうみ": { romaji: ["mizuumi"], meaning: "lake" },
    "あらし": { romaji: ["arashi"], meaning: "storm" },
    "あめ": { romaji: ["ame"], meaning: "rain" },
    "ゆき": { romaji: ["yuki"], meaning: "snow" },
    "そら": { romaji: ["sora"], meaning: "sky" },
    "ほし": { romaji: ["hoshi"], meaning: "star" },
    "つき": { romaji: ["tsuki"], meaning: "moon" },
    "やま": { romaji: ["yama"], meaning: "mountain" },
    "かわ": { romaji: ["kawa"], meaning: "river" },
    "うみ": { romaji: ["umi"], meaning: "sea" },
    "はな": { romaji: ["hana"], meaning: "flower" },
    "はる": { romaji: ["haru"], meaning: "spring" },
    "なつ": { romaji: ["natsu"], meaning: "summer" },
    "あき": { romaji: ["aki"], meaning: "autumn" },
    "ふゆ": { romaji: ["fuyu"], meaning: "winter" },
    "くも": { romaji: ["kumo"], meaning: "cloud" },
    "かぜ": { romaji: ["kaze"], meaning: "wind" },
    "たいよう": { romaji: ["taiyou"], meaning: "sun" },
    "にじ": { romaji: ["niji"], meaning: "rainbow" },
    "きり": { romaji: ["kiri"], meaning: "fog" },

    // --- FOOD & DRINK (たべもの・のみもの) ---
    "おにぎり": { romaji: ["onigiri"], meaning: "rice ball" },
    "たまご": { romaji: ["tamago"], meaning: "egg" },
    "さかな": { romaji: ["sakana"], meaning: "fish" },
    "くだもの": { romaji: ["kudamono"], meaning: "fruit" },
    "やさい": { romaji: ["yasai"], meaning: "vegetable" },
    "ごはん": { romaji: ["gohan"], meaning: "meal/rice" },
    "おちゃ": { romaji: ["ocha"], meaning: "green tea" },
    "おかし": { romaji: ["okashi"], meaning: "sweets" },
    "みそしる": { romaji: ["misoshiru"], meaning: "miso soup" },
    "てんぷら": { romaji: ["tenpura"], meaning: "tempura" },
    "さとう": { romaji: ["satou"], meaning: "sugar" },
    "しお": { romaji: ["shio"], meaning: "salt" },
    "わさび": { romaji: ["wasabi"], meaning: "wasabi" },
    "あずき": { romaji: ["azuki"], meaning: "red bean" },
    "おべんとう": { romaji: ["obentou"], meaning: "lunch box" },
    "のみもの": { romaji: ["nomimono"], meaning: "drink" },
    "たべもの": { romaji: ["tabemono"], meaning: "food" },
    "おかず": { romaji: ["okazu"], meaning: "side dish" },
    "おいしい": { romaji: ["oishii"], meaning: "delicious" },
    "まずい": { romaji: ["mazui"], meaning: "tastes bad" },

    // --- HOUSEHOLD & OBJECTS (いえ・もの) ---
    "つくえ": { romaji: ["tsukue"], meaning: "desk" },
    "ほうき": { romaji: ["houki"], meaning: "broom" },
    "かがみ": { romaji: ["kagami"], meaning: "mirror" },
    "とけい": { romaji: ["tokei"], meaning: "clock/watch" },
    "めがね": { romaji: ["megane"], meaning: "glasses" },
    "かばん": { romaji: ["kaban"], meaning: "bag" },
    "さいふ": { romaji: ["saifu"], meaning: "wallet" },
    "はさみ": { romaji: ["hasami"], meaning: "scissors" },
    "ふでばこ": { romaji: ["fudebako"], meaning: "pencil case" },
    "じしょ": { romaji: ["jisho"], meaning: "dictionary" },
    "しんぶん": { romaji: ["shinbun"], meaning: "newspaper" },
    "てがみ": { romaji: ["tegami"], meaning: "letter" },
    "ふとん": { romaji: ["futon"], meaning: "futon" },
    "まくら": { romaji: ["makura"], meaning: "pillow" },
    "せっけん": { romaji: ["sekken"], meaning: "soap" },
    "くつした": { romaji: ["kutsushita"], meaning: "socks" },
    "ぼうし": { romaji: ["boushi"], meaning: "hat" },
    "ゆかた": { romaji: ["yukata"], meaning: "yukata" },
    "いえ": { romaji: ["ie"], meaning: "house" },
    "まど": { romaji: ["mado"], meaning: "window" },
    "かぎ": { romaji: ["kagi"], meaning: "key" },
    "くつ": { romaji: ["kutsu"], meaning: "shoes" },
    "てぶくろ": { romaji: ["tebukuro"], meaning: "gloves" },
    "ちず": { romaji: ["chizu"], meaning: "map" },
    "えんぴつ": { romaji: ["enpitsu"], meaning: "pencil" },
    "ほん": { romaji: ["hon"], meaning: "book" },
    "かみ": { romaji: ["kami"], meaning: "paper" },

    // --- BODY PARTS (からだ) ---
    "あたま": { romaji: ["atama"], meaning: "head" },
    "おなか": { romaji: ["onaka"], meaning: "stomach" },
    "からだ": { romaji: ["karada"], meaning: "body" },
    "せなか": { romaji: ["senaka"], meaning: "back" },
    "こころ": { romaji: ["kokoro"], meaning: "heart" },
    "みみ": { romaji: ["mimi"], meaning: "ear" },
    "くち": { romaji: ["kuchi"], meaning: "mouth" },
    "め": { romaji: ["me"], meaning: "eye" },
    "て": { romaji: ["te"], meaning: "hand" },
    "あし": { romaji: ["ashi"], meaning: "leg/foot" },
    "ゆび": { romaji: ["yubi"], meaning: "finger" },
    "は": { romaji: ["ha"], meaning: "tooth" },
    "かた": { romaji: ["kata"], meaning: "shoulder" },
    "ひざ": { romaji: ["hiza"], meaning: "knee" },
    "ひじ": { romaji: ["hiji"], meaning: "elbow" },
    "くび": { romaji: ["kubi"], meaning: "neck" },
    "まゆげ": { romaji: ["mayuge"], meaning: "eyebrow" },
    "つめ": { romaji: ["tsume"], meaning: "nail" },

    // --- PEOPLE & FAMILY (ひと・かぞく) ---
    "ともだち": { romaji: ["tomodachi"], meaning: "friend" },
    "こども": { romaji: ["kodomo"], meaning: "child" },
    "おんな": { romaji: ["onna"], meaning: "woman" },
    "おとこ": { romaji: ["otoko"], meaning: "man" },
    "せんせい": { romaji: ["sensei"], meaning: "teacher" },
    "いしゃ": { romaji: ["isha"], meaning: "doctor" },
    "おかあさん": { romaji: ["okaasan"], meaning: "mother" },
    "おとうさん": { romaji: ["otousan"], meaning: "father" },
    "おねえさん": { romaji: ["oneesan"], meaning: "older sister" },
    "おにいさん": { romaji: ["oniisan"], meaning: "older brother" },
    "いもうと": { romaji: ["imouto"], meaning: "younger sister" },
    "おとうと": { romaji: ["otouto"], meaning: "younger brother" },
    "おじいさん": { romaji: ["ojiisan"], meaning: "grandfather" },
    "おばあさん": { romaji: ["obaasan"], meaning: "grandmother" },

    // --- PLACES & TRANSPORT (ばしょ・のりもの) ---
    "こうえん": { romaji: ["kouen"], meaning: "park" },
    "かいがん": { romaji: ["kaigan"], meaning: "coast" },
    "くるま": { romaji: ["kuruma"], meaning: "car" },
    "でんわ": { romaji: ["denwa"], meaning: "telephone" },
    "がっこう": { romaji: ["gakkou"], meaning: "school" },
    "えき": { romaji: ["eki"], meaning: "station" },
    "びょういん": { romaji: ["byouin"], meaning: "hospital" },
    "ぎんこう": { romaji: ["ginkou"], meaning: "bank" },
    "としょかん": { romaji: ["toshokan"], meaning: "library" },
    "ゆうびんきょく": { romaji: ["yuubinkyoku"], meaning: "post office" },
    "どうぶつえん": { romaji: ["doubutsuen"], meaning: "zoo" },
    "えいがかん": { romaji: ["eigakan"], meaning: "movie theater" },
    "きっさてん": { romaji: ["kissaten"], meaning: "cafe" },
    "でんしゃ": { romaji: ["densha"], meaning: "train" },
    "じてんしゃ": { romaji: ["jitensha"], meaning: "bicycle" },
    "ひこうき": { romaji: ["hikouki"], meaning: "airplane" },
    "ふね": { romaji: ["fune"], meaning: "ship/boat" },
    "ばす": { romaji: ["basu"], meaning: "bus" },
    "ちかてつ": { romaji: ["chikatetsu"], meaning: "subway" },

    // --- ADJECTIVES (けいようし) ---
    "あかるい": { romaji: ["akarui"], meaning: "bright" },
    "しずか": { romaji: ["shizuka"], meaning: "quiet" },
    "たのしい": { romaji: ["tanoshii"], meaning: "fun" },
    "うれしい": { romaji: ["ureshii"], meaning: "happy" },
    "かなしい": { romaji: ["kanashii"], meaning: "sad" },
    "はやい": { romaji: ["hayai"], meaning: "fast" },
    "おそい": { romaji: ["osoi"], meaning: "slow" },
    "あつい": { romaji: ["atsui"], meaning: "hot/thick" },
    "さむい": { romaji: ["samui"], meaning: "cold (weather)" },
    "つめたい": { romaji: ["tsumetai"], meaning: "cold to touch" },
    "きれい": { romaji: ["kirei"], meaning: "beautiful/clean" },
    "ちいさい": { romaji: ["chiisai"], meaning: "small" },
    "おおきい": { romaji: ["ookii"], meaning: "big" },
    "たかい": { romaji: ["takai"], meaning: "expensive/tall" },
    "やすい": { romaji: ["yasui"], meaning: "cheap" },
    "あたらしい": { romaji: ["atarashii"], meaning: "new" },
    "ふるい": { romaji: ["furui"], meaning: "old" },
    "むずかしい": { romaji: ["muzukashii"], meaning: "difficult" },
    "やさしい": { romaji: ["yasashii"], meaning: "easy/kind" },
    "とおい": { romaji: ["tooi"], meaning: "far" },
    "ちかい": { romaji: ["chikai"], meaning: "near" },
    "ひろい": { romaji: ["hiroi"], meaning: "wide" },
    "せまい": { romaji: ["semai"], meaning: "narrow" },
    "ねむい": { romaji: ["nemui"], meaning: "sleepy" },
    "つよい": { romaji: ["tsuyoi"], meaning: "strong" },
    "よわい": { romaji: ["yowai"], meaning: "weak" },

    // --- TIME & MISC (じかん・ほか) ---
    "あした": { romaji: ["ashita"], meaning: "tomorrow" },
    "きのう": { romaji: ["kinou"], meaning: "yesterday" },
    "きょう": { romaji: ["kyou"], meaning: "today" },
    "あさ": { romaji: ["asa"], meaning: "morning" },
    "よる": { romaji: ["yoru"], meaning: "night" },
    "ひる": { romaji: ["hiru"], meaning: "daytime" },
    "せかい": { romaji: ["sekai"], meaning: "world" },

    // --- COLORS (いろ) ---
    "あか": { romaji: ["aka"], meaning: "red" },
    "あお": { romaji: ["ao"], meaning: "blue" },
    "しろ": { romaji: ["shiro"], meaning: "white" },
    "くろ": { romaji: ["kuro"], meaning: "black" },
    "きいろ": { romaji: ["kiiro"], meaning: "yellow" },
    "みどり": { romaji: ["midori"], meaning: "green" },
    "ちゃいろ": { romaji: ["chairo"], meaning: "brown" },
    "むらさき": { romaji: ["murasaki"], meaning: "purple" },

    // --- NUMBERS (すうじ) ---
    "いち": { romaji: ["ichi"], meaning: "one" },
    "に": { romaji: ["ni"], meaning: "two" },
    "さん": { romaji: ["san"], meaning: "three" },
    "よん": { romaji: ["yon"], meaning: "four" },
    "ご": { romaji: ["go"], meaning: "five" },
    "ろく": { romaji: ["roku"], meaning: "six" },
    "なな": { romaji: ["nana"], meaning: "seven" },
    "はち": { romaji: ["hachi"], meaning: "eight" },
    "きゅう": { romaji: ["kyuu"], meaning: "nine" },
    "じゅう": { romaji: ["juu"], meaning: "ten" },
	
	// --- COUNTERS (つ) ---
    "ひとつ": { romaji: ["hitotsu"], meaning: "one (object)" },
    "ふたつ": { romaji: ["futatsu"], meaning: "two (objects)" },
    "みっつ": { romaji: ["mittsu"], meaning: "three (objects)" },
    "よっつ": { romaji: ["yottsu"], meaning: "four (objects)" },
    "いつつ": { romaji: ["itsutsu"], meaning: "five (objects)" },
    "むっつ": { romaji: ["muttsu"], meaning: "six (objects)" },
    "ななつ": { romaji: ["nanatsu"], meaning: "seven (objects)" },
    "やっつ": { romaji: ["yattsu"], meaning: "eight (objects)" },
    "ここのつ": { romaji: ["kokonotsu"], meaning: "nine (objects)" },
    "とお": { romaji: ["too"], meaning: "ten (objects)" },
    "いくつ": { romaji: ["ikutsu"], meaning: "how many?" },

    // --- VERBS (どうし) ---
    "たべる": { romaji: ["taberu"], meaning: "to eat" },
    "のむ": { romaji: ["nomu"], meaning: "to drink" },
    "ねる": { romaji: ["neru"], meaning: "to sleep" },
    "おきる": { romaji: ["okiru"], meaning: "to wake up" },
    "いく": { romaji: ["iku"], meaning: "to go" },
    "くる": { romaji: ["kuru"], meaning: "to come" },
    "かえる": { romaji: ["kaeru"], meaning: "to return home" },
    "みる": { romaji: ["miru"], meaning: "to see/watch" },
    "きく": { romaji: ["kiku"], meaning: "to listen" },
    "かく": { romaji: ["kaku"], meaning: "to write" },
    "よむ": { romaji: ["yomu"], meaning: "to read" },
    "はなす": { romaji: ["hanasu"], meaning: "to speak" },
    "かう": { romaji: ["kau"], meaning: "to buy" },
    "あそぶ": { romaji: ["asobu"], meaning: "to play" }
}
};