const MODES = {
  "Hiragana Gojūon": {
    "あ": { romaji: ["a"] }, "い": { romaji: ["i"] }, "う": { romaji: ["u"] }, "え": { romaji: ["e"] }, "お": { romaji: ["o"] },
    "か": { romaji: ["ka"] }, "き": { romaji: ["ki"] }, "く": { romaji: ["ku"] }, "け": { romaji: ["ke"] }, "こ": { romaji: ["ko"] },
    "さ": { romaji: ["sa"] }, "し": { romaji: ["shi"] }, "す": { romaji: ["su"] }, "せ": { romaji: ["se"] }, "そ": { romaji: ["so"] },
    "た": { romaji: ["ta"] }, "ち": { romaji: ["chi"] }, "つ": { romaji: ["tsu"] }, "て": { romaji: ["te"] }, "と": { romaji: ["to"] },
    "な": { romaji: ["na"] }, "に": { romaji: ["ni"] }, "ぬ": { romaji: ["nu"] }, "ね": { romaji: ["ne"] }, "の": { romaji: ["no"] },
    "は": { romaji: ["ha"] }, "ひ": { romaji: ["hi"] }, "ふ": { romaji: ["fu"] }, "へ": { romaji: ["he"] }, "ほ": { romaji: ["ho"] },
    "ま": { romaji: ["ma"] }, "み": { romaji: ["mi"] }, "む": { romaji: ["mu"] }, "め": { romaji: ["me"] }, "も": { romaji: ["mo"] },
    "や": { romaji: ["ya"] }, "ゆ": { romaji: ["yu"] }, "よ": { romaji: ["yo"] },
    "ら": { romaji: ["ra"] }, "り": { romaji: ["ri"] }, "る": { romaji: ["ru"] }, "れ": { romaji: ["re"] }, "ろ": { romaji: ["ro"] },
    "わ": { romaji: ["wa"] }, "を": { romaji: ["wo", "o"] }, "ん": { romaji: ["n"] }
  },

  "Hiragana Dakuon": {
    "が": { romaji: ["ga"] }, "ぎ": { romaji: ["gi"] }, "ぐ": { romaji: ["gu"] }, "げ": { romaji: ["ge"] }, "ご": { romaji: ["go"] },
    "ざ": { romaji: ["za"] }, "じ": { romaji: ["ji"] }, "ず": { romaji: ["zu"] }, "ぜ": { romaji: ["ze"] }, "ぞ": { romaji: ["zo"] },
    "だ": { romaji: ["da"] }, "ぢ": { romaji: ["ji"] }, "づ": { romaji: ["zu"] }, "で": { romaji: ["de"] }, "ど": { romaji: ["do"] },
    "ば": { romaji: ["ba"] }, "び": { romaji: ["bi"] }, "ぶ": { romaji: ["bu"] }, "べ": { romaji: ["be"] }, "ぼ": { romaji: ["bo"] },
    "ぱ": { romaji: ["pa"] }, "ぴ": { romaji: ["pi"] }, "ぷ": { romaji: ["pu"] }, "ぺ": { romaji: ["pe"] }, "ぽ": { romaji: ["po"] }
  },

  "Hiragana Yōon": {
    "きゃ": { romaji: ["kya"] }, "きゅ": { romaji: ["kyu"] }, "きょ": { romaji: ["kyo"] },
    "しゃ": { romaji: ["sha"] }, "しゅ": { romaji: ["shu"] }, "しょ": { romaji: ["sho"] },
    "ちゃ": { romaji: ["cha"] }, "ちゅ": { romaji: ["chu"] }, "ちょ": { romaji: ["cho"] },
    "にゃ": { romaji: ["nya"] }, "にゅ": { romaji: ["nyu"] }, "にょ": { romaji: ["nyo"] },
    "ひゃ": { romaji: ["hya"] }, "ひゅ": { romaji: ["hyu"] }, "ひょ": { romaji: ["hyo"] },
    "みゃ": { romaji: ["mya"] }, "みゅ": { romaji: ["myu"] }, "みょ": { romaji: ["myo"] },
    "りゃ": { romaji: ["rya"] }, "りゅ": { romaji: ["ryu"] }, "りょ": { romaji: ["ryo"] },
    "ぎゃ": { romaji: ["gya"] }, "ぎゅ": { romaji: ["gyu"] }, "ぎょ": { romaji: ["gyo"] },
    "じゃ": { romaji: ["ja"] }, "じゅ": { romaji: ["ju"] }, "じょ": { romaji: ["jo"] },
    "びゃ": { romaji: ["bya"] }, "びゅ": { romaji: ["byu"] }, "びょ": { romaji: ["byo"] },
    "ぴゃ": { romaji: ["pya"] }, "ぴゅ": { romaji: ["pyu"] }, "ぴょ": { romaji: ["pyo"] }
  },

  "Katakana Basic": {
    "ア": { romaji: ["a"] }, "イ": { romaji: ["i"] }, "ウ": { romaji: ["u"] }, "エ": { romaji: ["e"] }, "オ": { romaji: ["o"] },
    "カ": { romaji: ["ka"] }, "キ": { romaji: ["ki"] }, "ク": { romaji: ["ku"] }, "ケ": { romaji: ["ke"] }, "コ": { romaji: ["ko"] },
    "サ": { romaji: ["sa"] }, "シ": { romaji: ["shi"] }, "ス": { romaji: ["su"] }, "セ": { romaji: ["se"] }, "ソ": { romaji: ["so"] },
    "タ": { romaji: ["ta"] }, "チ": { romaji: ["chi"] }, "ツ": { romaji: ["tsu"] }, "テ": { romaji: ["te"] }, "ト": { romaji: ["to"] },
    "ナ": { romaji: ["na"] }, "ニ": { romaji: ["ni"] }, "ヌ": { romaji: ["nu"] }, "ネ": { romaji: ["ne"] }, "ノ": { romaji: ["no"] },
    "ハ": { romaji: ["ha"] }, "ヒ": { romaji: ["hi"] }, "フ": { romaji: ["fu"] }, "ヘ": { romaji: ["he"] }, "ほ": { romaji: ["ho"] },
    "マ": { romaji: ["ma"] }, "ミ": { romaji: ["mi"] }, "ム": { romaji: ["mu"] }, "メ": { romaji: ["me"] }, "モ": { romaji: ["mo"] },
    "ヤ": { romaji: ["ya"] }, "ユ": { romaji: ["yu"] }, "ヨ": { romaji: ["yo"] },
    "ラ": { romaji: ["ra"] }, "リ": { romaji: ["ri"] }, "ル": { romaji: ["ru"] }, "レ": { romaji: ["re"] }, "ロ": { romaji: ["ro"] },
    "ワ": { romaji: ["wa"] }, "ヲ": { romaji: ["wo"] }, "ン": { romaji: ["n"] }
  },

  "Katakana Dakuon": {
    "ガ": { romaji: ["ga"] }, "ギ": { romaji: ["gi"] }, "グ": { romaji: ["gu"] }, "ゲ": { romaji: ["ge"] }, "ゴ": { romaji: ["go"] },
    "ザ": { romaji: ["za"] }, "ジ": { romaji: ["ji"] }, "ズ": { romaji: ["zu"] }, "ゼ": { romaji: ["ze"] }, "ゾ": { romaji: ["zo"] },
    "ダ": { romaji: ["da"] }, "ヂ": { romaji: ["ji"] }, "ヅ": { romaji: ["zu"] }, "デ": { romaji: ["de"] }, "ド": { romaji: ["do"] },
    "バ": { romaji: ["ba"] }, "ビ": { romaji: ["bi"] }, "ブ": { romaji: ["bu"] }, "ベ": { romaji: ["be"] }, "ボ": { romaji: ["bo"] },
    "パ": { romaji: ["pa"] }, "ピ": { romaji: ["pi"] }, "プ": { romaji: ["pu"] }, "ペ": { romaji: ["pe"] }, "ポ": { romaji: ["po"] }
  },

  "Katakana Yōon": {
    "キャ": { romaji: ["kya"] }, "キュ": { romaji: ["kyu"] }, "キョ": { romaji: ["kyo"] },
    "シャ": { romaji: ["sha"] }, "シュ": { romaji: ["shu"] }, "ショ": { romaji: ["sho"] },
    "チャ": { romaji: ["cha"] }, "チュ": { romaji: ["chu"] }, "チョ": { romaji: ["cho"] },
    "ニャ": { romaji: ["nya"] }, "ニュ": { romaji: ["nyu"] }, "ニョ": { romaji: ["nyo"] },
    "ヒャ": { romaji: ["hya"] }, "ヒュ": { romaji: ["hyu"] }, "ヒョ": { romaji: ["hyo"] },
    "ミャ": { romaji: ["mya"] }, "ミュ": { romaji: ["myu"] }, "ミョ": { romaji: ["myo"] },
    "リャ": { romaji: ["rya"] }, "リュ": { romaji: ["ryu"] }, "リョ": { romaji: ["ryo"] },
    "ギャ": { romaji: ["gya"] }, "ギュ": { romaji: ["gyu"] }, "ギョ": { romaji: ["gyo"] },
    "ジャ": { romaji: ["ja"] }, "ジュ": { romaji: ["ju"] }, "ジョ": { romaji: ["jo"] },
    "ビャ": { romaji: ["bya"] }, "ビュ": { romaji: ["byu"] }, "ビョ": { romaji: ["byo"] },
    "ピャ": { romaji: ["pya"] }, "ピュ": { romaji: ["pyu"] }, "ピョ": { romaji: ["pyo"] }
  },

  "Vocabulary (Hiragana)": {
    "ねこ": { romaji: ["neko"], meaning: "cat" },
    "いぬ": { romaji: ["inu"], meaning: "dog" },
    "とり": { romaji: ["tori"], meaning: "bird" },
    "うさぎ": { romaji: ["usagi"], meaning: "rabbit" },
    "からす": { romaji: ["karasu"], meaning: "crow" },
    "きつね": { romaji: ["kitsune"], meaning: "fox" },
    "すずめ": { romaji: ["suzume"], meaning: "sparrow" },
    "たぬき": { romaji: ["tanuki"], meaning: "raccoon dog" },
    "ねずみ": { romaji: ["nezumi"], meaning: "mouse" },
    "ひつじ": { romaji: ["hitsuji"], meaning: "sheep" },
    "めだか": { romaji: ["medaka"], meaning: "killifish" },
    "くじら": { romaji: ["kujira"], meaning: "whale" },
    "さくら": { romaji: ["sakura"], meaning: "cherry blossom" },
    "ひまわり": { romaji: ["himawari"], meaning: "sunflower" },
    "あさがお": { romaji: ["asagao"], meaning: "morning glory" },
    "もみじ": { romaji: ["momiji"], meaning: "maple" },
    "たけのこ": { romaji: ["takenoko"], meaning: "bamboo shoot" },
    "かみなり": { romaji: ["kaminari"], meaning: "thunder" },
    "みずうみ": { romaji: ["mizuumi"], meaning: "lake" },
    "かいがん": { romaji: ["kaigan"], meaning: "coast" },
    "あらし": { romaji: ["arashi"], meaning: "storm" },
    "こうえん": { romaji: ["kouen"], meaning: "park" },
    "おにぎり": { romaji: ["onigiri"], meaning: "rice ball" },
    "たまご": { romaji: ["tamago"], meaning: "egg" },
    "さかな": { romaji: ["sakana"], meaning: "fish" },
    "くだもの": { romaji: ["kudamono"], meaning: "fruit" },
    "やさい": { romaji: ["yasai"], meaning: "vegetable" },
    "ごはん": { romaji: ["gohan"], meaning: "meal/rice" },
    "おちゃ": { romaji: ["ocha"], meaning: "green tea" },
    "おかし": { romaji: ["okashi"], meaning: "sweets" },
    "みそしる": { romaji: ["misoshiru"], meaning: "miso soup" },
    "てんぷら": { romaji: ["tenpura"], meaning: "tempura" },
    "さとう": { romaji: ["satou"], meaning: "sugar" },
    "しお": { romaji: ["shio"], meaning: "salt" },
    "わさび": { romaji: ["wasabi"], meaning: "wasabi" },
    "あずき": { romaji: ["azuki"], meaning: "red bean" },
    "おべんとう": { romaji: ["obentou"], meaning: "lunch box" },
    "のみもの": { romaji: ["nomimono"], meaning: "drink" },
    "たべもの": { romaji: ["tabemono"], meaning: "food" },
    "おかず": { romaji: ["okazu"], meaning: "side dish" },
    "つくえ": { romaji: ["tsukue"], meaning: "desk" },
    "ほうき": { romaji: ["houki"], meaning: "broom" },
    "かがみ": { romaji: ["kagami"], meaning: "mirror" },
    "くるま": { romaji: ["kuruma"], meaning: "car" },
    "でんわ": { romaji: ["denwa"], meaning: "telephone" },
    "とけい": { romaji: ["tokei"], meaning: "clock/watch" },
    "めがね": { romaji: ["megane"], meaning: "glasses" },
    "かばん": { romaji: ["kaban"], meaning: "bag" },
    "さいふ": { romaji: ["saifu"], meaning: "wallet" },
    "はさみ": { romaji: ["hasami"], meaning: "scissors" },
    "ふでばこ": { romaji: ["fudebako"], meaning: "pencil case" },
    "じしょ": { romaji: ["jisho"], meaning: "dictionary" },
    "しんぶん": { romaji: ["shinbun"], meaning: "newspaper" },
    "てがみ": { romaji: ["tegami"], meaning: "letter" },
    "ふとん": { romaji: ["futon"], meaning: "futon" },
    "まくら": { romaji: ["makura"], meaning: "pillow" },
    "せっけん": { romaji: ["sekken"], meaning: "soap" },
    "くつした": { romaji: ["kutsushita"], meaning: "socks" },
    "ぼうし": { romaji: ["boushi"], meaning: "hat" },
    "ゆかた": { romaji: ["yukata"], meaning: "yukata" },
    "あたま": { romaji: ["atama"], meaning: "head" },
    "おなか": { romaji: ["onaka"], meaning: "stomach" },
    "からだ": { romaji: ["karada"], meaning: "body" },
    "せなか": { romaji: ["senaka"], meaning: "back" },
    "こころ": { romaji: ["kokoro"], meaning: "heart" },
    "ともだち": { romaji: ["tomodachi"], meaning: "friend" },
    "こども": { romaji: ["kodomo"], meaning: "child" },
    "おんな": { romaji: ["onna"], meaning: "woman" },
    "おとこ": { romaji: ["otoko"], meaning: "man" },
    "せんせい": { romaji: ["sensei"], meaning: "teacher" },
    "いしゃ": { romaji: ["isha"], meaning: "doctor" },
    "あかるい": { romaji: ["akarui"], meaning: "bright" },
    "しずか": { romaji: ["shizuka"], meaning: "quiet" },
    "たのしい": { romaji: ["tanoshii"], meaning: "fun" },
    "うれしい": { romaji: ["ureshii"], meaning: "happy" },
    "かなしい": { romaji: ["kanashii"], meaning: "sad" },
    "はやい": { romaji: ["hayai"], meaning: "fast" },
    "おそい": { romaji: ["osoi"], meaning: "slow" },
    "あつい": { romaji: ["atsui"], meaning: "hot" },
    "さむい": { romaji: ["samui"], meaning: "cold" },
    "つめたい": { romaji: ["tsumetai"], meaning: "cold to touch" },
    "きれい": { romaji: ["kirei"], meaning: "beautiful/clean" },
    "ちいさい": { romaji: ["chiisai"], meaning: "small" },
    "おおきい": { romaji: ["ookii"], meaning: "big" },
    "あした": { romaji: ["ashita"], meaning: "tomorrow" },
    "きのう": { romaji: ["kinou"], meaning: "yesterday" },
    "きょう": { romaji: ["kyou"], meaning: "today" },
    "せかい": { romaji: ["sekai"], meaning: "world" },
    "あめ": { romaji: ["ame"], meaning: "rain" },
    "ゆき": { romaji: ["yuki"], meaning: "snow" },
    "そら": { romaji: ["sora"], meaning: "sky" },
    "ほし": { romaji: ["hoshi"], meaning: "star" },
    "つき": { romaji: ["tsuki"], meaning: "moon" },
    "やま": { romaji: ["yama"], meaning: "mountain" },
    "かわ": { romaji: ["kawa"], meaning: "river" },
    "うみ": { romaji: ["umi"], meaning: "sea" },
    "はな": { romaji: ["hana"], meaning: "flower" },
    "いえ": { romaji: ["ie"], meaning: "house" },
    "まど": { romaji: ["mado"], meaning: "window" },
    "かぎ": { romaji: ["kagi"], meaning: "key" },
    "くつ": { romaji: ["kutsu"], meaning: "shoes" },
    "てぶくろ": { romaji: ["tebukuro"], meaning: "gloves" },
    "あさ": { romaji: ["asa"], meaning: "morning" },
    "よる": { romaji: ["yoru"], meaning: "night" },
    "ひる": { romaji: ["hiru"], meaning: "daytime" },
    "ちず": { romaji: ["chizu"], meaning: "map" },
    "えんぴつ": { romaji: ["enpitsu"], meaning: "pencil" },
    "ほん": { romaji: ["hon"], meaning: "book" },
    "かみ": { romaji: ["kami"], meaning: "paper" },
    "みみ": { romaji: ["mimi"], meaning: "ear" },
    "くち": { romaji: ["kuchi"], meaning: "mouth" },
    "め": { romaji: ["me"], meaning: "eye" },
    "て": { romaji: ["te"], meaning: "hand" }
  },

  "Vocabulary (Katakana) ": {
    "カメラ": { romaji: ["kamera"], meaning: "camera" },
    "テレビ": { romaji: ["terebi"], meaning: "TV" },
    "ラジオ": { romaji: ["rajio"], meaning: "radio" },
    "パソコン": { romaji: ["pasokon"], meaning: "PC/laptop" },
    "スマホ": { romaji: ["sumaho"], meaning: "smartphone" },
    "コーヒー": { romaji: ["ko-hi-", "koohi", "koohii", "kohi"], meaning: "coffee" },
    "コーラ": { romaji: ["ko-ra", "koora", "kora"], meaning: "cola" },
    "ビール": { romaji: ["bi-ru", "biiru", "biru"], meaning: "beer" },
    "ワイン": { romaji: ["wain"], meaning: "wine" },
    "パン": { romaji: ["pan"], meaning: "bread" },
    "ケーキ": { romaji: ["ke-ki", "keeki", "keki"], meaning: "cake" },
    "アイス": { romaji: ["aisu"], meaning: "ice cream" },
    "サラダ": { romaji: ["sarada"], meaning: "salad" },
    "チーズ": { romaji: ["chi-zu", "chiizu", "chizu"], meaning: "cheese" },
    "パスタ": { romaji: ["pasuta"], meaning: "pasta" },
    "ホテル": { romaji: ["hoteru"], meaning: "hotel" },
    "トイレ": { romaji: ["toire"], meaning: "toilet/bathroom" },
    "ビル": { romaji: ["biru"], meaning: "building" },
    "タクシー": { romaji: ["takushi-", "takushii", "takushi"], meaning: "taxi" },
    "バス": { romaji: ["basu"], meaning: "bus" },
    "ドア": { romaji: ["doa"], meaning: "door" },
    "ニュース": { romaji: ["nyu-su", "nyuusu", "nyusu"], meaning: "news" },
    "プレゼント": { romaji: ["purezento"], meaning: "present" },
    "テニス": { romaji: ["tenisu"], meaning: "tennis" },
    "サッカー": { romaji: ["sakka-", "sakkii", "sakka"], meaning: "soccer" },
    "ピアノ": { romaji: ["piano"], meaning: "piano" },
    "ギター": { romaji: ["gita-", "gitaa", "gita"], meaning: "guitar" },
    "シャツ": { romaji: ["shatsu"], meaning: "shirt" },
    "ズボン": { romaji: ["zubon"], meaning: "pants" },
    "ネクタイ": { romaji: ["nekutai"], meaning: "necktie" },
    "ノート": { romaji: ["no-to", "nooto", "noto"], meaning: "notebook" },
    "ペン": { romaji: ["pen"], meaning: "pen" },
    "クラス": { romaji: ["kurasu"], meaning: "class" },
    "レストラン": { romaji: ["resutoran"], meaning: "restaurant" },
    "デパート": { romaji: ["depa-to", "depaato", "depato"], meaning: "department store" },
    "アメリカ": { romaji: ["amerika"], meaning: "USA" },
    "イギリス": { romaji: ["igirisu"], meaning: "UK" },
    "フランス": { romaji: ["furansu"], meaning: "france" },
    "メニュー": { romaji: ["menyu-", "menyuu", "menyu"], meaning: "menu" },
    "ジュース": { romaji: ["ju-su", "juusu", "jusu"], meaning: "juice" },
    "サンダル": { romaji: ["sandaru"], meaning: "sandals" },
    "ハンカチ": { romaji: ["hankachi"], meaning: "handkerchief" },
    "フォーク": { romaji: ["fo-ku", "fooku", "foku"], meaning: "fork" },
    "ナイフ": { romaji: ["naifu"], meaning: "knife" },
    "スプーン": { romaji: ["supu-n", "supuun", "supun"], meaning: "spoon" },
    "コップ": { romaji: ["koppu"], meaning: "glass/cup" },
    "キッチン": { romaji: ["kitchin"], meaning: "kitchen" },
    "ベッド": { romaji: ["beddo"], meaning: "bed" },
    "ソファ": { romaji: ["sofa"], meaning: "sofa" },
    "シャワー": { romaji: ["shawa-", "shawaa", "shawa"], meaning: "shower" },
    "エレベーター": { romaji: ["erebe-ta-", "erebeetaa"], meaning: "elevator" },
    "エアコン": { romaji: ["eakon"], meaning: "air conditioner" },
    "チケット": { romaji: ["chiketto"], meaning: "ticket" },
    "カレンダー": { romaji: ["karenda-", "karendaa"], meaning: "calendar" },
    "ボールペン": { romaji: ["bo-rupen"], meaning: "ballpoint pen" },
    "スポーツ": { romaji: ["supo-tsu", "supootsu"], meaning: "sports" },
    "ダンス": { romaji: ["dansu"], meaning: "dance" },
    "ドラム": { romaji: ["doramu"], meaning: "drums" },
    "ネコ": { romaji: ["neko"], meaning: "cat" },
    "ドイツ": { romaji: ["doitsu"], meaning: "Germany" },
    "イタリア": { romaji: ["itaria"], meaning: "Italy" },
    "スペイン": { romaji: ["supein"], meaning: "Spain" }
  }
};
