// kana-data.js
const MODES = {
    "Gojūon (Hiragana)": {
        "あ": "a", "い": "i", "う": "u", "え": "e", "お": "o",
        "か": "ka", "き": "ki", "く": "ku", "け": "ke", "こ": "ko",
        "さ": "sa", "し": "shi", "す": "su", "せ": "se", "そ": "so",
        "た": "ta", "ち": "chi", "つ": "tsu", "て": "te", "と": "to",
        "な": "na", "に": "ni", "ぬ": "nu", "ね": "ne", "の": "no",
        "は": "ha", "ひ": "hi", "ふ": "fu", "へ": "he", "ほ": "ho",
        "ま": "ma", "み": "mi", "む": "mu", "め": "me", "も": "mo",
        "や": "ya", "ゆ": "yu", "よ": "yo",
        "ら": "ra", "り": "ri", "る": "ru", "れ": "re", "ろ": "ro",
        "わ": "wa", "を": ["wo", "o"], "ん": "n"
    },
    "Dakuon (Hiragana)": {
        "が": "ga", "ぎ": "gi", "ぐ": "gu", "げ": "ge", "ご": "go",
        "ざ": "za", "じ": "ji", "ず": "zu", "ぜ": "ze", "ぞ": "zo",
        "だ": "da", "ぢ": "ji", "づ": "zu", "で": "de", "ど": "do",
        "ば": "ba", "び": "bi", "ぶ": "bu", "べ": "be", "ぼ": "bo",
        "ぱ": "pa", "ぴ": "pi", "ぷ": "pu", "ぺ": "pe", "ぽ": "po"
    },
    "Yōon (Hiragana)": {
        "きゃ": "kya", "きゅ": "kyu", "きょ": "kyo",
        "しゃ": "sha", "しゅ": "shu", "しょ": "sho",
        "ちゃ": "cha", "ちゅ": "chu", "ちょ": "cho",
        "にゃ": "nya", "にゅ": "nyu", "にょ": "nyo",
        "ひゃ": "hya", "ひゅ": "hyu", "ひょ": "hyo",
        "みゃ": "mya", "みゅ": "myu", "みょ": "myo",
        "りゃ": "rya", "りゅ": "ryu", "りょ": "ryo",
        "ぎゃ": "gya", "ぎゅ": "gyu", "ぎょ": "gyo",
        "じゃ": "ja", "じゅ": "ju", "じょ": "jo",
        "びゃ": "bya", "びゅ": "byu", "びょ": "byo",
        "ぴゃ": "pya", "ぴゅ": "pyu", "ぴょ": "pyo"
    },
    "Katakana Basic": {
        "ア": "a", "イ": "i", "ウ": "u", "エ": "e", "オ": "o",
        "カ": "ka", "キ": "ki", "ク": "ku", "ケ": "ke", "コ": "ko",
        "サ": "sa", "シ": "shi", "ス": "su", "セ": "se", "ソ": "so",
        "タ": "ta", "チ": "chi", "ツ": "tsu", "テ": "te", "ト": "to",
        "ナ": "na", "ニ": "ni", "ヌ": "nu", "ネ": "ne", "ノ": "no",
        "ハ": "ha", "ヒ": "hi", "フ": "fu", "ヘ": "he", "ホ": "ho",
        "マ": "ma", "ミ": "mi", "ム": "mu", "メ": "me", "モ": "mo",
        "ヤ": "ya", "ユ": "yu", "ヨ": "yo",
        "ラ": "ra", "リ": "ri", "ル": "ru", "レ": "re", "ロ": "ro",
        "ワ": "wa", "ヲ": "wo", "ン": "n"
    },
    "Katakana Dakuon": {
        "ガ": "ga", "ギ": "gi", "グ": "gu", "ゲ": "ge", "ゴ": "go",
        "ザ": "za", "ジ": "ji", "ズ": "zu", "ゼ": "ze", "ゾ": "zo",
        "ダ": "da", "ヂ": "ji", "ヅ": "zu", "デ": "de", "ド": "do",
        "バ": "ba", "ビ": "bi", "ブ": "bu", "ベ": "be", "ボ": "bo",
        "パ": "pa", "ピ": "pi", "プ": "pu", "ペ": "pe", "ポ": "po"
    },
    "Katakana Yōon": {
        "キャ": "kya", "キュ": "kyu", "キョ": "kyo",
        "シャ": "sha", "シュ": "shu", "ショ": "sho",
        "チャ": "cha", "チュ": "chu", "チョ": "cho",
        "ニャ": "nya", "ニュ": "nyu", "ニョ": "nyo",
        "ヒャ": "hya", "ヒュ": "hyu", "ヒョ": "hyo",
        "ミゃ": "mya", "ミュ": "myu", "ミョ": "myo",
        "リャ": "rya", "リュ": "ryu", "リョ": "ryo",
        "ギャ": "gya", "ギュ": "gyu", "ギョ": "gyo",
        "ジャ": "ja", "ジュ": "ju", "ジョ": "jo",
        "ビャ": "bya", "ビュ": "byu", "ビョ": "byo",
        "ピャ": "pya", "ピュ": "pyu", "ピョ": "pyo"
    },
    "Vocabulary (Hiragana)": {
        "ねこ": "neko (Cat)", "いぬ": "inu (Dog)", "とり": "tori (Bird)", "うさぎ": "usagi (Rabbit)", 
        "からす": "karasu (Crow)", "きつね": "kitsune (Fox)", "すずめ": "suzume (Sparrow)",
        "たぬき": "tanuki (Raccoon Dog)", "ねずみ": "nezumi (Mouse)", "ひつじ": "hitsuji (Sheep)",
        "みだか": "medaka (Killifish)", "くじら": "kujira (Whale)", "さくら": "sakura (Cherry Blossom)", 
        "ひまわり": "himawari (Sunflower)", "あさがお": "asagao (Morning Glory)", "もみじ": "momiji (Maple)", 
        "たけのこ": "takenoko (Bamboo Shoot)", "かみなり": "kaminari (Thunder)", "みずうみ": "mizuumi (Lake)", 
        "かいがん": "kaigan (Coast)", "あらし": "arashi (Storm)", "こうえん": "kouen (Park)",
        "おにぎり": "onigiri (Rice Ball)", "たまご": "tamago (Egg)", "さかな": "sakana (Fish)", 
        "くだもの": "kudamono (Fruit)", "やさい": "yasai (Vegetable)", "ごはん": "gohan (Meal/Rice)", 
        "おちゃ": "ocha (Green Tea)", "おかし": "okashi (Sweets)", "みそしる": "misoshiru (Miso Soup)", 
        "てんぷら": "tenpura (Tempura)", "さとう": "satou (Sugar)", "しお": "shio (Salt)",
        "わさび": "wasabi (Wasabi)", "あずき": "azuki (Red Bean)", "おべんとう": "obentou (Lunch Box)", 
        "のみもの": "nomimono (Drink)", "たべもの": "tabemono (Food)", "おかず": "okazu (Side Dish)",
        "つくえ": "tsukue (Desk)", "ほうき": "houki (Broom)", "かがみ": "kagami (Mirror)", 
        "くるま": "kuruma (Car)", "でんわ": "denwa (Telephone)", "とけい": "tokei (Clock/Watch)", 
        "めがね": "megane (Glasses)", "かばん": "kaban (Bag)", "さいふ": "saifu (Wallet)", 
        "はさみ": "hasami (Scissors)", "ふでばこ": "fudebako (Pencil Case)", "じしょ": "jisho (Dictionary)",
        "しんぶん": "shinbun (Newspaper)", "てがみ": "tegami (Letter)", "ふとん": "futon (Futon)", 
        "まくら": "makura (Pillow)", "せっけん": "sekken (Soap)", "くつした": "kutsushita (Socks)", 
        "ぼうし": "boushi (Hat)", "ゆかた": "yukata (Yukata)", "あたま": "atama (Head)", 
        "おなか": "onaka (Stomach)", "からだ": "karada (Body)", "せなか": "senaka (Back)",
        "こころ": "kokoro (Heart)", "ともだち": "tomodachi (Friend)", "こども": "kodomo (Child)",
        "おんな": "onna (Woman)", "おとこ": "otoko (Man)", "せんせい": "sensei (Teacher)", 
        "いしゃ": "isha (Doctor)", "あかるい": "akarui (Bright)", "しずか": "shizuka (Quiet)", 
        "たのしい": "tanoshii (Fun)", "うれしい": "ureshii (Happy)", "かなしい": "kanashii (Sad)", 
        "はやい": "hayai (Fast)", "おそい": "osoi (Slow)", "あつい": "atsui (Hot)",
        "さむい": "samui (Cold)", "つめたい": "tsumetai (Cold to touch)", "きれい": "kirei (Beautiful/Clean)", 
        "ちいさい": "chiisai (Small)", "おおきい": "ookii (Big)", "あした": "ashita (Tomorrow)",
        "きのう": "kinou (Yesterday)", "きょう": "kyou (Today)", "せかい": "sekai (World)",
        "あめ": "ame (Rain)", "ゆき": "yuki (Snow)", "そら": "sora (Sky)", "ほし": "hoshi (Star)",
        "つき": "tsuki (Moon)", "やま": "yama (Mountain)", "かわ": "kawa (River)", "うみ": "umi (Sea)",
        "はな": "hana (Flower)", "いえ": "ie (House)", "まど": "mado (Window)", "かぎ": "kagi (Key)",
        "くつ": "kutsu (Shoes)", "てぶくろ": "tebukuro (Gloves)", "あさ": "asa (Morning)", "よる": "yoru (Night)",
        "ひる": "hiru (Daytime)", "ちず": "chizu (Map)", "えんぴつ": "enpitsu (Pencil)", "ほん": "hon (Book)",
        "かみ": "kami (Paper)", "みみ": "mimi (Ear)", "くち": "kuchi (Mouth)", "め": "me (Eye)", "て": "te (Hand)"
    },
    "Vocabulary (Katakana)": {
        "カメラ": "kamera (Camera)", "テレビ": "terebi (TV)", "ラジオ": "rajio (Radio)",
        "パソコン": "pasokon (PC/Laptop)", "スマホ": "sumaho (Smartphone)", "コーヒー": ["ko-hi-", "koohi", "koohii", "kohi"],
        "コーラ": ["ko-ra", "koora", "kora"], "ビール": ["bi-ru", "biiru", "biru"], "ワイン": "wain (Wine)",
        "パン": "pan (Bread)", "ケーキ": ["ke-ki", "keeki", "keki"], "アイス": "aisu (Ice Cream)",
        "サラダ": "sarada (Salad)", "チーズ": ["chi-zu", "chiizu", "chizu"], "パスタ": "pasuta (Pasta)",
        "ホテル": "hoteru (Hotel)", "トイレ": "toire (Toilet/Bathroom)", "ビル": "biru (Building)",
        "タクシー": ["takushi-", "takushii", "takushi"], "バス": "basu (Bus)", "ドア": "doa (Door)",
        "ニュース": ["nyu-su", "nyuusu", "nyusu"], "プレゼント": "purezento (Present)", "テニス": "tenisu (Tennis)",
        "サッカー": ["sakka-", "sakkii", "sakka"], "ピアノ": "piano (Piano)", "ギター": ["gita-", "gitaa", "gita"],
        "シャツ": "shatsu (Shirt)", "ズボン": "zubon (Pants)", "ネクタイ": "nekutai (Necktie)",
        "ノート": ["no-to", "nooto", "noto"], "ペン": "pen (Pen)", "クラス": "kurasu (Class)",
        "レストラン": "resutoran (Restaurant)", "デパート": ["depa-to", "depaato", "depato"],
        "アメリカ": "amerika (USA)", "イギリス": "igirisu (UK)", "フランス": "furansu (France)",
        "メニュー": ["menyu-", "menyuu", "menyu"], "ジュース": ["ju-su", "juusu", "jusu"],
        "サンダル": "sandaru (Sandals)", "ハンカチ": "hankachi (Handkerchief)", "フォーク": ["fo-ku", "fooku", "foku"],
        "ナイフ": "naifu (Knife)", "スプーン": ["supu-n", "supuun", "supun"], "コップ": "koppu (Glass/Cup)",
        "キッチン": "kitchin (Kitchen)", "ベッド": "beddo (Bed)", "ソファ": "sofa (Sofa)",
        "シャワー": ["shawa-", "shawaa", "shawa"], "エレベーター": ["erebe-ta-", "erebeetaa"],
        "エアコン": "eakon (Air Conditioner)", "チケット": "chiketto (Ticket)", "カレンダー": ["karenda-", "karendaa"],
        "ボールペン": "bo-rupen (Ballpoint Pen)", "スポーツ": ["supo-tsu", "supootsu"], "ダンス": "dansu (Dance)",
        "ドラム": "doramu (Drums)", "ネコ": "neko (Cat)", "ドイツ": "doitsu (Germany)",
        "イタリア": "itaria (Italy)", "スペイン": "supein (Spain)"
    }
};
